name: phpproject
services:

  webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    depends_on:
      - mysql
    restart: always
    networks:
      phpproject:

  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'TheOnlyPassRoot'
      MYSQL_DB: 'sonitamysql'
      MYSQL_USER: 'sonitamysql'
      MYSQL_PASSWORD: 'PassForSonita!'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      phpproject:

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "9002:80"
    environment:
      PMA_HOST: mysql
    networks:
      phpproject:

volumes:
  mysql_data:

#All containers need to be on the same network to connect to each other
networks:
  phpproject:

